--- 
title: "How the 2016 US Election Happened"
author: "An Phi"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: blacksteed232/elexion
description: "A study using data mining to see the relationship between demographic factors and the 2016 election result by county in the USA"
---

# Introduction {-}
_"Why!"_ exclaimed our friends in disappointment as we all witness Hillary Clinton losing Pennsylvania. To some extent, we could relate to them; we were also puzzled by this outcome: Hillary did swamp Donald Trump in the popular vote, but she lost the major battle. In fact, before the fateful night, most people believed that she was the "meant to be" and so the following morning, the result they would read on the newspapers would be exactly just that. But perhaps, politics at time can be quite unpredictable. Or is it? Instead of awing at the perplexity of the matter, perhaps, we can take a more mature and scientific approach to this by studying the 2016 election result and try to figure out ourselves how things actually happened. Nevertheless, all is tied to the word "perhaps", and we might actually end up learning nothing about this subject matter. But let no pessimism haunt our path and let us move on to the real question "What do we wish to learn?" we have contemplated this question for quite a some time and there are three goals we want to achieve. First, we want to understand how various factors (demographic, geographic and even historical) influence the result. Based on this, we would need to collect data that correspond to the factors we mentioned, but unlike geographic and demographic data, historical data is really hard to be collected in mass, not to say to be quantified and classified in general. As such, we humbly limit our history factor to just recent past years' election results (i.e 2008 and 2012). In terms of the granularity of the data set, we will use the results by county (that will yield us a suitable size for our data set). This choice also comes from the fact that despite the smallest election division being precinct, county is the smallest division which we can collect demographic and geographic data. But to nobody's surprise, past election result can be a really strong predictor of the 2016 election outcome. As such, our second concern comes quite naturally: if we only consider demographic and geographic factors, can we actually build a model to predict the result for each county. Our concern is that whether or not the state where a county belongs to can affect the vote. Perhaps, including the state in the model might sounds dubious but because when we talk about election, we often say it in the form of _"Mr./Mrs. won state X"_ and also because being a voter living in a state that has been voting for a single party for 50 years might affect a person's choice just like how families, friends, and neighbors might affect your choice of vote, we feel that state is justified to be in the data set. As for demographic attributes, our view is that we will include common demographic factors such as: age, life expectancy, income inequality, race and ethnicity, etc. We also include crime and weather data, which at first glance might seem extremely unlikely to be useful in our model but we will be very vigilant in our feature selection step to make sure redundant and irrelevant features will not be included while we train our model. To follow the convention, we will take the CRISP-DM model approach. Of course, we can refer to the questions we are trying to solve as our _"buisness goals"_ but we are not really trying to solve any business problem, we will not formally document our business understanding. Neither do we wish to deploy our learned model in the end to predict future election results (however, we will have a subsection dedicated to explaining what we learned that might prove helpful to political parties based on the models learned; in the CRISP-DM sense, this is part of the deployment procedure). As such, we will deliver our [data quality report](#dqr) (DQR) to explain our attempts at getting to know the data, as well as our [data quality plan](#dqp) (DQP) to provide detailed procedures of how we prepare the data and a [report](#rep) which succinctly sums up our approach and discusses in detail the learned models along with their performance evaluations and interpretations. We also include a short [section](#md) dedicated to explaining the process of choosing the classifiers, preparation for tuning their parameters and pre-processing steps required for the data set prior to modelling. We name our report "A 'Minority' Report" with the intention to explicate how Donald Trump won the election despite the popular (majority) prediction, and so we hope that people who find the results unsettling and unfair (or even unjust) or people who seek relief via conspiracy theories will take a few minutes to see what numbers and figures have to say about this election.

# Disclaimer {-}
Apprently, the election data provided by [USA.county.data](https://github.com/Deleetdk/USA.county.data) is scapred from the New York Times, who bought the data set from Associated Press. Since this might have complicated legal issue, we wish to express that we are not responsible for the election data as we are just taking it _as is_ from the noted source. Also, since this is data-mining project, we wish to show the step through which we clean and transform the data set so that people can reproduce the results that we obtained, as such, it is almost impossible to not have the election data anywhere in this repository. For healthcare and human-development data sets, we also have to include them in our project because we use them for data preparation step. As such, we just really want to express that we use this data set merely for study purpose and have NO intention to redistribute, nor to commercialize it in anyway. So please __do not cite us__ as the source of these data sets if you choose to use them yourselves. Please refer to the original sources of these data files as we have detailed in section \@ref(datasources).  

This project was built as part of our class project, all conclusion obtained in the paper are based on data-mining, figures and numbers. We do not want the results to be used in anyway to favor any party, i.e. we take a political-free and neutral stance while working on this project. Also, we deem ourselves as lacking both political understanding and data-mining related knowledge so the results obtained might just be taken lightly and should not be cited in any publications.